#!/usr/bin/python3
import fileinput
sep = "\", \""
for line in fileinput.input():
	la = line.split('|')
	if (la[19] == ""):
		sql = "INSERT INTO citation (\n"
		sql = sql + "\tCID, VJPID, First_Name, Last_Name, Address, City, State, Zip, Date_of_Birth, Jurisdiction, Citation_Number, Case_Number, Court_Date, Charges, Violation_Date, Fine_Amount, Appearance"
		sql = sql + "\n) VALUES (\n"
		sql = sql + "\t" + la[0] + ", \"" + la[1] + sep + la[3] + sep + la[2] + sep + la[5] + sep + la[6] + sep + la[7] + sep + la[8] + sep + la[9] + sep + la[13] + sep + la[10] + sep + la[11] + sep + la[15] + sep + la[14] + sep + la[12] + sep + la[17] + "\", " + la[16] + ""
		sql = sql + "\n)\nON DUPLICATE KEY UPDATE\n"
		sql = sql + "\tCID=" + la[0] + ", "
		sql = sql + "VJPID=" + la[1] + ", "
		sql = sql + "First_Name=\"" + la[3] + "\", "
		sql = sql + "Last_Name=\"" + la[2] + "\", "
		sql = sql + "Address=\"" + la[5] + "\", "
		sql = sql + "City=\"" + la[6] + "\", "
		sql = sql + "State=\"" + la[7] + "\", "
		sql = sql + "Zip=\"" + la[8] + "\", "
		sql = sql + "Date_of_Birth=\"" + la[9] + "\", "
		sql = sql + "Jurisdiction=\"" + la[13] + "\", "
		sql = sql + "Citation_Number=\"" + la[10] + "\", "
		sql = sql + "Case_Number=\"" + la[11] + "\", "
		sql = sql + "Court_date=\"" + la[15] + "\", "
		sql = sql + "Charges=\"" + la[14] + "\", "
		sql = sql + "Violation_Date=\"" + la[12] + "\", "
		sql = sql + "Fine_Amount=\"" + la[17] + "\", "
		sql = sql + "Appearance=" + la[16] + ";\n"
		print(sql)
	elif (la[14] != "Court Automation Fee"):
		sql = "INSERT INTO timepay (\n"
		sql = sql + "\tCID, VJPID, First_Name, Last_Name, Address, City, State, Zip, Date_of_Birth, Jurisdiction, Contract_Num, Min_Payment, Case_Number, Court_Date, Charges, Violation_Date, Fine_Amount, Appearance" 
		sql = sql + "\n) VALUES (\n"
		sql = sql +  "\t" + la[0] + ", \"" + la[1] + sep + la[3] + sep + la[2] + sep + la[5] + sep + la[6] + sep + la[7] + sep + la[8] + sep + la[9] + sep + la[13] + sep + la[19] + sep + la[21] + sep + la[11] + sep + la[15] + sep + la[14] + sep + la[12] + sep + la[17] + "\", " + la[16] + ""
		sql = sql + "\n)\nON DUPLICATE KEY UPDATE\n"
		sql = sql + "\tCID=" + la[0] + ", "
		sql = sql + "VJPID=" + la[1] + ", "
		sql = sql + "First_Name=\"" + la[3] + "\", "
		sql = sql + "Last_Name=\"" + la[2] + "\", "
		sql = sql + "Address=\"" + la[5] + "\", "
		sql = sql + "City=\"" + la[6] + "\", "
		sql = sql + "State=\"" + la[7] + "\", "
		sql = sql + "Zip=\"" + la[8] + "\", "
		sql = sql + "Date_of_Birth=\"" + la[9] + "\", "
		sql = sql + "Jurisdiction=\"" + la[13] + "\", "
		sql = sql + "Contract_Num=\"" + la[19] + "\", "
		sql = sql + "Min_Payment=\"" + la[21] + "\", "
		sql = sql + "Case_Number=\"" + la[11] + "\", "
		sql = sql + "Court_Date=\"" + la[15] + "\", "
		sql = sql + "Charges=\"" + la[14] + "\", "
		sql = sql + "Violation_Date=\"" + la[12] + "\", "
		sql = sql + "Fine_Amount=\"" + la[17] + "\", "
		sql = sql + "Appearance=" + la[16] + ";\n"
		print(sql) 
